name: Update Token List

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    

jobs:
  update:
    name: Update Token List To Solflare Spec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          
      - name: Install Deps
        run: npm ci

      - name: Fetch & Update Resources
        run: node .

      - name: Commit Changes
        uses: test-room-7/action-update-file@v1
        with:
          file-path: token-list.json
          commit-msg: Daily List Update
          github-token: ${{ secrets.GITHUB_TOKEN }}